from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("about/", views.about, name="about"),
    path("rules/", views.admission_rules, name="admission_rules"),
    path("documents/", views.admission_documents, name="admission_documents"),
    path("schedule/", views.admission_schedule, name="admission_schedule"),
    path("news/", views.news_list, name="news_list"),
    path("news/<slug:slug>/", views.news_detail, name="news_detail"),
    path("programs/", views.program_list, name="program_list"),
    path("programs/<int:pk>/", views.program_detail, name="program_detail"),
    path("faculties/", views.faculty_list, name="faculty_list"),
    path("faq/", views.faq_list, name="faq_list"),
    path("contacts/", views.contact_list, name="contact_list"),
    path("campaigns/", views.campaign_list, name="campaign_list"),
    path("register/", views.register, name="register"),
    path("login/", views.user_login, name="login"),
    path("logout/", views.user_logout, name="logout"),
    path("dashboard/applicant/", views.applicant_dashboard, name="applicant_dashboard"),
    path(
        "dashboard/applicant/applications/",
        views.applicant_applications,
        name="applicant_applications",
    ),
    path(
        "dashboard/applicant/documents/",
        views.applicant_documents,
        name="applicant_documents",
    ),
    path(
        "dashboard/applicant/results/",
        views.applicant_results,
        name="applicant_results",
    ),
    path("dashboard/profile/", views.profile_edit, name="profile_edit"),
    path("dashboard/methodist/", views.methodist_dashboard, name="methodist_dashboard"),
    path(
        "dashboard/methodist/applications/",
        views.methodist_applications,
        name="methodist_applications",
    ),
    path(
        "dashboard/methodist/documents/",
        views.methodist_documents,
        name="methodist_documents",
    ),
    path(
        "dashboard/methodist/templates/",
        views.methodist_templates,
        name="methodist_templates",
    ),
    path("dashboard/admin/", views.admin_dashboard, name="admin_dashboard"),
    path("dashboard/admin/users/", views.admin_users, name="admin_users"),
    path(
        "dashboard/admin/applications/",
        views.admin_applications,
        name="admin_applications",
    ),
    path("dashboard/admin/programs/", views.admin_programs, name="admin_programs"),
    path("dashboard/admin/campaigns/", views.admin_campaigns, name="admin_campaigns"),
    path("dashboard/admin/reports/", views.admin_reports, name="admin_reports"),
    path("applications/create/", views.application_create, name="application_create"),
    path("applications/<int:pk>/", views.application_detail, name="application_detail"),
    path(
        "applications/<int:pk>/review/",
        views.application_review,
        name="application_review",
    ),
    path(
        "applications/<int:pk>/export/docx/",
        views.export_application_docx,
        name="export_application_docx",
    ),
    path(
        "applications/export/xlsx/",
        views.export_applications_xlsx,
        name="export_applications_xlsx",
    ),
    path(
        "applications/<int:application_id>/upload/",
        views.document_upload,
        name="document_upload",
    ),
    path(
        "documents/<int:pk>/download/",
        views.download_document,
        name="download_document",
    ),
    path("documents/<int:pk>/verify/", views.verify_document, name="verify_document"),
    path(
        "generated/<str:filename>/download/",
        views.download_generated,
        name="download_generated",
    ),
    path("exam-results/create/", views.exam_result_create, name="exam_result_create"),
]
